# Generated by Django 5.1 on 2024-09-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mproduct", "0002_brand_alter_plans_brand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plans",
            old_name="user",
            new_name="owner",
        ),
    ]
