# Generated by Django 5.1 on 2024-09-07 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mproduct", "0003_rename_user_plans_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plans",
            name="owner",
        ),
        migrations.AlterField(
            model_name="plans",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together={("owner", "name")},
        ),
    ]
