# Generated by Django 5.1 on 2024-09-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mproduct", "0004_remove_plans_owner_alter_plans_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plans",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
