# Generated by Django 5.1 on 2024-09-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mproduct", "0005_alter_plans_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscribers",
            name="admin",
        ),
    ]
