# Generated by Django 5.1 on 2024-09-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mproduct", "0006_remove_subscribers_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscribers",
            old_name="Purchased on",
            new_name="purchased_on",
        ),
        migrations.RenameField(
            model_name="subscribers",
            old_name="Subscription status",
            new_name="subscription_status",
        ),
    ]
