# Generated by Django 5.1 on 2024-09-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mproduct", "0007_rename_purchased_on_subscribers_purchased_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plans",
            name="duration",
            field=models.IntegerField(help_text="Duration of the plan"),
        ),
    ]
